
// == Generated by -psid- on  1 Jul 2018@23:22:08 ==

clear

// == [ Family file 1999 ] == 
use ER13002 ER13005 ER13005E ER13006 ER13008A ER13009 ER13011 ER13012 ER13013 ER13021 ER13037 ER13040 ER13041 ER13045 ER13047 ER13054 ER13056 ER13078 ER13079 ER13205 ER13206 ER13207 ER13208 ER13498 ER13717 ER13718 ER13719 ER13720 ER14010 ER14256 ER14757 ER15115 ER15116 ER15117 ER15121 ER15122 ER15126 ER15127 ER15809 ER15818 ER15928 ER16430 ER16431C ER16454 ER16460 ER16462 ER16463 ER16465 ER16471 ER16482 ER16514 ER16515 ER16515A1 ER16515A2 ER16515A3 ER16515A4 ER16515A5 ER16515A6 ER16515A7 ER16515A8 ER16515A9 ER16515B1 ER16515B6 ER16515B7 ER16515B8 ER16515B9 ER16515C1 ER16515C2 ER16515C3 ER16515C4 ER16515C5 ER16515C6 ER16515C7 ER16515C8 ER16515C9 ER16515D1 ER16515D2 ER16515D6 ER16516 ER16517 ER16518 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam1999er"', clear
ren ER13002 x11102_1999
replace x11102_1999 = . if x11102_1999==0
sort x11102_1999
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000001, replace

// == [ Family file 2001 ] == 
use ER17002 ER17005 ER17006 ER17007 ER17009 ER17012 ER17014 ER17015 ER17016 ER17024 ER17040 ER17043 ER17044 ER17050 ER17052 ER17061 ER17063 ER17089 ER17090 ER17216 ER17217 ER17218 ER17219 ER17538 ER17786 ER17787 ER17788 ER17789 ER18109 ER18387 ER18930 ER19311 ER19312 ER19313 ER19317 ER19318 ER19322 ER19323 ER19870 ER19879 ER19989 ER20376 ER20377C ER20394 ER20399 ER20410 ER20443 ER20447 ER20450 ER20451 ER20452 ER20455 ER20456 ER20456A1 ER20456A2 ER20456A3 ER20456A4 ER20456A5 ER20456A6 ER20456A7 ER20456A8 ER20456A9 ER20456B1 ER20456B6 ER20456B7 ER20456B8 ER20456B9 ER20456C1 ER20456C2 ER20456C3 ER20456C4 ER20456C5 ER20456C6 ER20456C7 ER20456C8 ER20456C9 ER20456D1 ER20456D2 ER20456D6 ER20457 ER20458 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2001er"', clear
ren ER17002 x11102_2001
replace x11102_2001 = . if x11102_2001==0
sort x11102_2001
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000002, replace

// == [ Family file 2003 ] == 
use ER21002 ER21004 ER21005 ER21007 ER21012 ER21016 ER21018 ER21019 ER21020 ER21023 ER21039 ER21042 ER21043 ER21049 ER21051 ER21060 ER21062 ER21118 ER21119 ER21123 ER21124 ER21125 ER21126 ER21184 ER21341 ER21373 ER21374 ER21375 ER21376 ER21434 ER21653 ER22300 ER22706 ER22707 ER22708 ER22712 ER22713 ER22717 ER22718 ER23307 ER23316 ER23426 ER24080 ER24091 ER24099 ER24101 ER24104 ER24116 ER24135 ER24137 ER24138 ER24138A1 ER24138A2 ER24138A3 ER24138A4 ER24138A5 ER24138A6 ER24138A7 ER24138A8 ER24138A9 ER24138B1 ER24138B6 ER24138B7 ER24138B8 ER24138B9 ER24138C1 ER24138C2 ER24138C3 ER24138C4 ER24138C5 ER24138C6 ER24138C7 ER24138C8 ER24138C9 ER24138D1 ER24138D2 ER24138D6 ER24143 ER24144A ER24148 ER24149 ER24179 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2003er"', clear
ren ER21002 x11102_2003
replace x11102_2003 = . if x11102_2003==0
sort x11102_2003
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000003, replace

// == [ Family file 2005 ] == 
use ER25002 ER25004 ER25005 ER25007 ER25012 ER25016 ER25018 ER25019 ER25020 ER25023 ER25027 ER25028 ER25029 ER25040 ER25042 ER25051 ER25053 ER25099 ER25100 ER25104 ER25105 ER25106 ER25107 ER25173 ER25330 ER25362 ER25363 ER25364 ER25365 ER25431 ER25655 ER26281 ER26687 ER26688 ER26689 ER26693 ER26694 ER26698 ER26699 ER27267 ER27277 ER27393 ER27886 ER27897 ER27931 ER27943 ER28002 ER28003 ER28004 ER28031 ER28033 ER28035 ER28037 ER28037A1 ER28037A2 ER28037A3 ER28037A4 ER28037A5 ER28037A6 ER28037A7 ER28037A8 ER28037A9 ER28037B1 ER28037B6 ER28037B7 ER28037B8 ER28037B9 ER28037C1 ER28037C2 ER28037C3 ER28037C4 ER28037C5 ER28037C6 ER28037C7 ER28037C8 ER28037C9 ER28037D1 ER28037D2 ER28037D3 ER28037D7 ER28037D8 ER28037D9 ER28037E1 ER28037E2 ER28037E3 ER28042 ER28043A ER28047 ER28048 ER28078 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2005er"', clear
ren ER25002 x11102_2005
replace x11102_2005 = . if x11102_2005==0
sort x11102_2005
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000004, replace

// == [ Family file 2007 ] == 
use ER36002 ER36004 ER36005 ER36007 ER36012 ER36016 ER36018 ER36019 ER36020 ER36023 ER36027 ER36028 ER36029 ER36040 ER36042 ER36052 ER36054 ER36104 ER36105 ER36109 ER36110 ER36111 ER36112 ER36178 ER36335 ER36367 ER36368 ER36369 ER36370 ER36436 ER36673 ER37299 ER37705 ER37706 ER37707 ER37711 ER37712 ER37716 ER37717 ER40442 ER40452 ER40565 ER40876 ER40887 ER40921 ER40933 ER40992 ER40993 ER40994 ER41021 ER41023 ER41025 ER41027 ER41027A1 ER41027A2 ER41027A3 ER41027A4 ER41027A5 ER41027A6 ER41027A7 ER41027A8 ER41027A9 ER41027B1 ER41027B6 ER41027B7 ER41027B8 ER41027B9 ER41027C1 ER41027C2 ER41027C3 ER41027C4 ER41027C5 ER41027C6 ER41027C7 ER41027C8 ER41027C9 ER41027D1 ER41027D2 ER41027D3 ER41027D7 ER41027D8 ER41027D9 ER41027E1 ER41027E2 ER41027E3 ER41032 ER41033A ER41037 ER41038 ER41069 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2007er"', clear
ren ER36002 x11102_2007
replace x11102_2007 = . if x11102_2007==0
sort x11102_2007
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000005, replace

// == [ Family file 2009 ] == 
use ER42002 ER42004 ER42005 ER42007 ER42012 ER42016 ER42018 ER42019 ER42020 ER42023 ER42028 ER42029 ER42030 ER42041 ER42043 ER42060 ER42062 ER42133 ER42134 ER42140 ER42141 ER42142 ER42143 ER42211 ER42362 ER42392 ER42393 ER42394 ER42395 ER42463 ER42692 ER43290 ER43696 ER43697 ER43698 ER43702 ER43703 ER43707 ER43708 ER46414 ER46424 ER46543 ER46767 ER46788 ER46829 ER46841 ER46900 ER46901 ER46902 ER46929 ER46931 ER46933 ER46935 ER46938 ER46942 ER46950 ER46954 ER46964 ER46966 ER46967 ER46968 ER46970 ER46971A1 ER46971A2 ER46971A3 ER46971A4 ER46971A5 ER46971A6 ER46971A7 ER46971A8 ER46971A9 ER46971B1 ER46971B6 ER46971B7 ER46971B8 ER46971B9 ER46971C1 ER46971C2 ER46971C3 ER46971C4 ER46971C5 ER46971C6 ER46971C7 ER46971C8 ER46971C9 ER46971D1 ER46971D2 ER46971D3 ER46971D7 ER46971D8 ER46971D9 ER46971E1 ER46971E2 ER46971E3 ER46974 ER46975A ER46981 ER46982 ER47012 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2009er"', clear
ren ER42002 x11102_2009
replace x11102_2009 = . if x11102_2009==0
sort x11102_2009
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000006, replace

// == [ Family file 2011 ] == 
use ER47302 ER47304 ER47305 ER47307 ER47312 ER47316 ER47318 ER47319 ER47320 ER47323 ER47328 ER47329 ER47330 ER47346 ER47348 ER47367 ER47369 ER47441 ER47442 ER47448 ER47449 ER47450 ER47451 ER47524 ER47675 ER47705 ER47706 ER47707 ER47708 ER47781 ER48008 ER48615 ER49041 ER49042 ER49043 ER49047 ER49048 ER49052 ER49053 ER51775 ER51785 ER51904 ER52175 ER52196 ER52237 ER52249 ER52308 ER52309 ER52310 ER52337 ER52339 ER52341 ER52343 ER52346 ER52350 ER52354 ER52358 ER52368 ER52390 ER52391 ER52392 ER52394 ER52395A1 ER52395A2 ER52395A3 ER52395A4 ER52395A5 ER52395A6 ER52395A7 ER52395A8 ER52395A9 ER52395B1 ER52395B6 ER52395B7 ER52395B8 ER52395B9 ER52395C1 ER52395C2 ER52395C3 ER52395C4 ER52395C5 ER52395C6 ER52395C7 ER52395C8 ER52395C9 ER52395D1 ER52395D2 ER52395D3 ER52395D7 ER52395D8 ER52395D9 ER52395E1 ER52395E2 ER52395E3 ER52398 ER52399A ER52405 ER52406 ER52436 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2011er"', clear
ren ER47302 x11102_2011
replace x11102_2011 = . if x11102_2011==0
sort x11102_2011
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000007, replace

// == [ Family file 2013 ] == 
use ER53002 ER53004 ER53005 ER53007 ER53012 ER53016 ER53018 ER53019 ER53020 ER53023 ER53028 ER53029 ER53030 ER53046 ER53048 ER53067 ER53069 ER53141 ER53142 ER53148 ER53149 ER53150 ER53151 ER53224 ER53375 ER53411 ER53412 ER53413 ER53414 ER53487 ER53705 ER54309 ER54797 ER54798 ER54799 ER54803 ER54804 ER54808 ER54809 ER57512 ER57522 ER57659 ER57976 ER57997 ER58038 ER58050 ER58117 ER58118 ER58119 ER58146 ER58148 ER58150 ER58152 ER58155 ER58157 ER58161 ER58165 ER58167 ER58171 ER58181 ER58207 ER58208 ER58209 ER58211 ER58212A1 ER58212A2 ER58212A3 ER58212A4 ER58212A5 ER58212A6 ER58212A7 ER58212A8 ER58212A9 ER58212B1 ER58212B6 ER58212B7 ER58212B8 ER58212B9 ER58212C1 ER58212C2 ER58212C3 ER58212C4 ER58212C5 ER58212C6 ER58212C7 ER58212C8 ER58212C9 ER58212D1 ER58212D2 ER58212D3 ER58212D7 ER58212D8 ER58212D9 ER58212E1 ER58212E2 ER58212E3 ER58215 ER58216 ER58223 ER58224 ER58257 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2013er"', clear
ren ER53002 x11102_2013
replace x11102_2013 = . if x11102_2013==0
sort x11102_2013
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000008, replace

// == [ Family file 2015 ] == 
use ER60002 ER60004 ER60005 ER60007 ER60012 ER60016 ER60018 ER60019 ER60021 ER60024 ER60029 ER60030 ER60031 ER60047 ER60049 ER60068 ER60070 ER60156 ER60157 ER60163 ER60164 ER60165 ER60166 ER60239 ER60390 ER60426 ER60427 ER60428 ER60429 ER60502 ER60720 ER61349 ER61908 ER61910 ER61913 ER61918 ER61921 ER61926 ER61929 ER64634 ER64644 ER64810 ER65156 ER65177 ER65216 ER65244 ER65314 ER65315 ER65316 ER65343 ER65345 ER65347 ER65349 ER65352 ER65354 ER65358 ER65362 ER65364 ER65368 ER65378 ER65404 ER65405 ER65406 ER65408 ER65410 ER65411 ER65412 ER65413 ER65414 ER65415 ER65416 ER65417 ER65418 ER65419 ER65424 ER65425 ER65426 ER65427 ER65428 ER65429 ER65430 ER65431 ER65432 ER65433 ER65434 ER65435 ER65436 ER65437 ER65438 ER65439 ER65443 ER65444 ER65445 ER65446 ER65447 ER65448 ER65451 ER65452 ER65459 ER65460 ER65492 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/fam2015er"', clear
ren ER60002 x11102_2015
replace x11102_2015 = . if x11102_2015==0
sort x11102_2015
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000009, replace

// == [ Wealth file 1999 ] == 
use S?01 S403 S405 S409 S411 S416 S417 S419 S420 S420A using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/wlth1999"', clear
ren S?01 x11102_1999
replace x11102_1999 = . if x11102_1999 == 0
sort x11102_1999
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000a, replace

// == [ Wealth file 2001 ] == 
use S?01 S503 S505 S509 S511 S516 S517 S519 S520 S520A using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/wlth2001"', clear
ren S?01 x11102_2001
replace x11102_2001 = . if x11102_2001 == 0
sort x11102_2001
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000b, replace

// == [ Wealth file 2003 ] == 
use S?01 S603 S605 S609 S611 S616 S617 S619 S620 S620A using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/wlth2003"', clear
ren S?01 x11102_2003
replace x11102_2003 = . if x11102_2003 == 0
sort x11102_2003
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000c, replace

// == [ Wealth file 2005 ] == 
use S?01 S703 S705 S709 S711 S716 S717 S719 S720 S720A using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/wlth2005"', clear
ren S?01 x11102_2005
replace x11102_2005 = . if x11102_2005 == 0
sort x11102_2005
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000d, replace

// == [ Wealth file 2007 ] == 
use S?01 S803 S805 S809 S811 S816 S817 S819 S820 S820A using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/wlth2007"', clear
ren S?01 x11102_2007
replace x11102_2007 = . if x11102_2007 == 0
sort x11102_2007
save /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000e, replace

// == [ Individual file ] == 
use ER30002 ER30001 ER33501 ER33601 ER33701 ER33801 ER33901 ER34001 ER34101 ER34201 ER34301 ER33502 ER33602 ER33702 ER33802 ER33902 ER34002 ER34102 ER34202 ER34302 ER33603 ER33604 ER33606 ER33612 ER33637 ER33639 ER33703 ER33704 ER33706 ER33712 ER33740 ER33742 ER33803 ER33804 ER33806 ER33813 ER33848 ER33849 ER33903 ER33904 ER33906 ER33913 ER33950 ER33951 ER34003 ER34004 ER34006 ER34016 ER34045 ER34046 ER34103 ER34104 ER34106 ER34116 ER34154 ER34155 ER34203 ER34204 ER34206 ER34216 ER34268 ER34269 ER34303 ER34305 ER34307 ER34317 ER34376 ER34413 ER34414 ER33503 ER33504 ER33506 ER33512 ER33546 ER33547 ER32000 ER32050 using `"/Users/bibekbasnet/Documents/GitHub/RetirementConsumptionPSID/Data/Raw/PSID_Install/ind2015er"'
gen long x11101ll = ER30001*1000 + ER30002
lab var x11101ll "Person identification number"
ren ER33501 x11102_1999
replace x11102_1999 = . if x11102_1999 == 0
ren ER33502 xsqnr_1999
ren ER33601 x11102_2001
replace x11102_2001 = . if x11102_2001 == 0
ren ER33602 xsqnr_2001
ren ER33701 x11102_2003
replace x11102_2003 = . if x11102_2003 == 0
ren ER33702 xsqnr_2003
ren ER33801 x11102_2005
replace x11102_2005 = . if x11102_2005 == 0
ren ER33802 xsqnr_2005
ren ER33901 x11102_2007
replace x11102_2007 = . if x11102_2007 == 0
ren ER33902 xsqnr_2007
ren ER34001 x11102_2009
replace x11102_2009 = . if x11102_2009 == 0
ren ER34002 xsqnr_2009
ren ER34101 x11102_2011
replace x11102_2011 = . if x11102_2011 == 0
ren ER34102 xsqnr_2011
ren ER34201 x11102_2013
replace x11102_2013 = . if x11102_2013 == 0
ren ER34202 xsqnr_2013
ren ER34301 x11102_2015
replace x11102_2015 = . if x11102_2015 == 0
ren ER34302 xsqnr_2015
gen byte __000000 = 0
replace __000000 = __000000 + 1 if inrange(xsqnr_1999,1,20) | inrange(xsqnr_1999,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2001,1,20) | inrange(xsqnr_2001,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2003,1,20) | inrange(xsqnr_2003,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2005,1,20) | inrange(xsqnr_2005,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2007,1,20) | inrange(xsqnr_2007,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2009,1,20) | inrange(xsqnr_2009,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2011,1,20) | inrange(xsqnr_2011,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2013,1,20) | inrange(xsqnr_2013,81,89)
replace __000000 = __000000 + 1 if inrange(xsqnr_2015,1,20) | inrange(xsqnr_2015,81,89)
keep if __000000 >= 1
drop __000000
capture drop ER30002
capture drop ER30001

// == [ Merge files] == 
merge m:1 x11102_1999 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000001 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2001 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000002 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2003 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000003 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2005 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000004 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2007 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000005 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2009 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000006 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2011 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000007 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2013 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000008 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2015 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.000009 , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_1999 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000a , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2001 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000b , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2003 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000c , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2005 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000d , keep(1 3 4 5) update
drop _merge
merge m:1 x11102_2007 using /var/folders/m4/b9lmhyms3r16qtq8123xwgrw0000gn/T//S_06405.00000e , keep(1 3 4 5) update
drop _merge

// == [ Rename Variables ] == 
ren ER33503 rel2head1999
ren ER33603 rel2head2001
ren ER33703 rel2head2003
ren ER33803 rel2head2005
ren ER33903 rel2head2007
ren ER34003 rel2head2009
ren ER34103 rel2head2011
ren ER34203 rel2head2013
ren ER34303 rel2head2015
ren ER33504 age1999
ren ER33604 age2001
ren ER33704 age2003
ren ER33804 age2005
ren ER33904 age2007
ren ER34004 age2009
ren ER34104 age2011
ren ER34204 age2013
ren ER34305 age2015
ren ER33506 year_born1999
ren ER33606 year_born2001
ren ER33706 year_born2003
ren ER33806 year_born2005
ren ER33906 year_born2007
ren ER34006 year_born2009
ren ER34106 year_born2011
ren ER34206 year_born2013
ren ER34307 year_born2015
ren ER13011 sex_head1999
ren ER17014 sex_head2001
ren ER21018 sex_head2003
ren ER25018 sex_head2005
ren ER36018 sex_head2007
ren ER42018 sex_head2009
ren ER47318 sex_head2011
ren ER53018 sex_head2013
ren ER60018 sex_head2015
ren ER32000 sex_indiv
ren ER32050 deathyr
ren ER13006 month1999
ren ER17009 month2001
ren ER21012 month2003
ren ER25012 month2005
ren ER36012 month2007
ren ER42012 month2009
ren ER47312 month2011
ren ER53012 month2013
ren ER60012 month2015
ren ER13008A fchg1999
ren ER17007 fchg2001
ren ER21007 fchg2003
ren ER25007 fchg2005
ren ER36007 fchg2007
ren ER42007 fchg2009
ren ER47307 fchg2011
ren ER53007 fchg2013
ren ER60007 fchg2015
ren ER13005E splitoff_indicator1999
ren ER17006 splitoff_indicator2001
ren ER21005 splitoff_indicator2003
ren ER25005 splitoff_indicator2005
ren ER36005 splitoff_indicator2007
ren ER42005 splitoff_indicator2009
ren ER47305 splitoff_indicator2011
ren ER53005 splitoff_indicator2013
ren ER60005 splitoff_indicator2015
ren ER13012 age_spouse1999
ren ER17015 age_spouse2001
ren ER21019 age_spouse2003
ren ER25019 age_spouse2005
ren ER36019 age_spouse2007
ren ER42019 age_spouse2009
ren ER47319 age_spouse2011
ren ER53019 age_spouse2013
ren ER60019 age_spouse2015
ren ER13013 children1999
ren ER17016 children2001
ren ER21020 children2003
ren ER25020 children2005
ren ER36020 children2007
ren ER42020 children2009
ren ER47320 children2011
ren ER53020 children2013
ren ER60021 children2015
ren ER13021 married1999
ren ER17024 married2001
ren ER21023 married2003
ren ER25023 married2005
ren ER36023 married2007
ren ER42023 married2009
ren ER47323 married2011
ren ER53023 married2013
ren ER60024 married2015
ren ER15928 racehead1999
ren ER19989 racehead2001
ren ER23426 racehead2003
ren ER27393 racehead2005
ren ER40565 racehead2007
ren ER46543 racehead2009
ren ER51904 racehead2011
ren ER57659 racehead2013
ren ER64810 racehead2015
ren ER16516 educhead1999
ren ER20457 educhead2001
ren ER24148 educhead2003
ren ER28047 educhead2005
ren ER41037 educhead2007
ren ER46981 educhead2009
ren ER52405 educhead2011
ren ER58223 educhead2013
ren ER65459 educhead2015
ren ER16517 educspouse1999
ren ER20458 educspouse2001
ren ER24149 educspouse2003
ren ER28048 educspouse2005
ren ER41038 educspouse2007
ren ER46982 educspouse2009
ren ER52406 educspouse2011
ren ER58224 educspouse2013
ren ER65460 educspouse2015
ren ER15818 spouse_mother_educlevel1999
ren ER19879 spouse_mother_educlevel2001
ren ER23316 spouse_mother_educlevel2003
ren ER27277 spouse_mother_educlevel2005
ren ER40452 spouse_mother_educlevel2007
ren ER46424 spouse_mother_educlevel2009
ren ER51785 spouse_mother_educlevel2011
ren ER57522 spouse_mother_educlevel2013
ren ER64644 spouse_mother_educlevel2015
ren ER15809 spouse_father_educlevel1999
ren ER19870 spouse_father_educlevel2001
ren ER23307 spouse_father_educlevel2003
ren ER27267 spouse_father_educlevel2005
ren ER40442 spouse_father_educlevel2007
ren ER46414 spouse_father_educlevel2009
ren ER51775 spouse_father_educlevel2011
ren ER57512 spouse_father_educlevel2013
ren ER64634 spouse_father_educlevel2015
ren ER13009 fsize1999
ren ER17012 fsize2001
ren ER21016 fsize2003
ren ER25016 fsize2005
ren ER36016 fsize2007
ren ER42016 fsize2009
ren ER47316 fsize2011
ren ER53016 fsize2013
ren ER60016 fsize2015
ren ER16430 region1999
ren ER20376 region2001
ren ER24143 region2003
ren ER28042 region2005
ren ER41032 region2007
ren ER46974 region2009
ren ER52398 region2011
ren ER58215 region2013
ren ER65451 region2015
ren ER16431C metro_pre20151999
ren ER20377C metro_pre20152001
ren ER24144A metro_pre20152003
ren ER28043A metro_pre20152005
ren ER41033A metro_pre20152007
ren ER46975A metro_pre20152009
ren ER52399A metro_pre20152011
ren ER58216 metro_pre20152013
ren ER65452 metro_20152015
ren ER13205 emp_status_head1999
ren ER17216 emp_status_head2001
ren ER21123 emp_status_head2003
ren ER25104 emp_status_head2005
ren ER36109 emp_status_head2007
ren ER42140 emp_status_head2009
ren ER47448 emp_status_head2011
ren ER53148 emp_status_head2013
ren ER60163 emp_status_head2015
ren ER13206 emp_status_head_21999
ren ER17217 emp_status_head_22001
ren ER21124 emp_status_head_22003
ren ER25105 emp_status_head_22005
ren ER36110 emp_status_head_22007
ren ER42141 emp_status_head_22009
ren ER47449 emp_status_head_22011
ren ER53149 emp_status_head_22013
ren ER60164 emp_status_head_22015
ren ER13207 emp_status_head_31999
ren ER17218 emp_status_head_32001
ren ER21125 emp_status_head_32003
ren ER25106 emp_status_head_32005
ren ER36111 emp_status_head_32007
ren ER42142 emp_status_head_32009
ren ER47450 emp_status_head_32011
ren ER53150 emp_status_head_32013
ren ER60165 emp_status_head_32015
ren ER13208 ret_year1999
ren ER17219 ret_year2001
ren ER21126 ret_year2003
ren ER25107 ret_year2005
ren ER36112 ret_year2007
ren ER42143 ret_year2009
ren ER47451 ret_year2011
ren ER53151 ret_year2013
ren ER60166 ret_year2015
ren ER13498 why_last_job_end1999
ren ER17538 why_last_job_end2001
ren ER21184 why_last_job_end2003
ren ER25173 why_last_job_end2005
ren ER36178 why_last_job_end2007
ren ER42211 why_last_job_end2009
ren ER47524 why_last_job_end2011
ren ER53224 why_last_job_end2013
ren ER60239 why_last_job_end2015
ren ER21341 months_out_lab_force2003
ren ER25330 months_out_lab_force2005
ren ER36335 months_out_lab_force2007
ren ER42362 months_out_lab_force2009
ren ER47675 months_out_lab_force2011
ren ER53375 months_out_lab_force2013
ren ER60390 months_out_lab_force2015
ren ER13717 emp_status_spouse1999
ren ER17786 emp_status_spouse2001
ren ER21373 emp_status_spouse2003
ren ER25362 emp_status_spouse2005
ren ER36367 emp_status_spouse2007
ren ER42392 emp_status_spouse2009
ren ER47705 emp_status_spouse2011
ren ER53411 emp_status_spouse2013
ren ER60426 emp_status_spouse2015
ren ER13718 emp_status_spouse_21999
ren ER17787 emp_status_spouse_22001
ren ER21374 emp_status_spouse_22003
ren ER25363 emp_status_spouse_22005
ren ER36368 emp_status_spouse_22007
ren ER42393 emp_status_spouse_22009
ren ER47706 emp_status_spouse_22011
ren ER53412 emp_status_spouse_22013
ren ER60427 emp_status_spouse_22015
ren ER13719 emp_status_spouse_31999
ren ER17788 emp_status_spouse_32001
ren ER21375 emp_status_spouse_32003
ren ER25364 emp_status_spouse_32005
ren ER36369 emp_status_spouse_32007
ren ER42394 emp_status_spouse_32009
ren ER47707 emp_status_spouse_32011
ren ER53413 emp_status_spouse_32013
ren ER60428 emp_status_spouse_32015
ren ER13720 ret_year_spouse1999
ren ER17789 ret_year_spouse2001
ren ER21376 ret_year_spouse2003
ren ER25365 ret_year_spouse2005
ren ER36370 ret_year_spouse2007
ren ER42395 ret_year_spouse2009
ren ER47708 ret_year_spouse2011
ren ER53414 ret_year_spouse2013
ren ER60429 ret_year_spouse2015
ren ER14010 why_last_job_end_spouse1999
ren ER18109 why_last_job_end_spouse2001
ren ER21434 why_last_job_end_spouse2003
ren ER25431 why_last_job_end_spouse2005
ren ER36436 why_last_job_end_spouse2007
ren ER42463 why_last_job_end_spouse2009
ren ER47781 why_last_job_end_spouse2011
ren ER53487 why_last_job_end_spouse2013
ren ER60502 why_last_job_end_spouse2015
ren ER33512 emp_status_indiv1999
ren ER33612 emp_status_indiv2001
ren ER33712 emp_status_indiv2003
ren ER33813 emp_status_indiv2005
ren ER33913 emp_status_indiv2007
ren ER34016 emp_status_indiv2009
ren ER34116 emp_status_indiv2011
ren ER34216 emp_status_indiv2013
ren ER34317 emp_status_indiv2015
ren ER16462 inc_fam1999
ren ER20456 inc_fam2001
ren ER24099 inc_fam2003
ren ER28037 inc_fam2005
ren ER41027 inc_fam2007
ren ER46935 inc_fam2009
ren ER52343 inc_fam2011
ren ER58152 inc_fam2013
ren ER65349 inc_fam2015
ren ER16463 inc_head1999
ren ER20443 inc_head2001
ren ER24116 inc_head2003
ren ER27931 inc_head2005
ren ER40921 inc_head2007
ren ER46829 inc_head2009
ren ER52237 inc_head2011
ren ER58038 inc_head2013
ren ER65216 inc_head2015
ren ER16465 inc_spouse1999
ren ER20447 inc_spouse2001
ren ER24135 inc_spouse2003
ren ER27943 inc_spouse2005
ren ER40933 inc_spouse2007
ren ER46841 inc_spouse2009
ren ER52249 inc_spouse2011
ren ER58050 inc_spouse2013
ren ER65244 inc_spouse2015
ren ER14757 inc_spouse_all1999
ren ER18930 inc_spouse_all2001
ren ER22300 inc_spouse_all2003
ren ER26281 inc_spouse_all2005
ren ER37299 inc_spouse_all2007
ren ER43290 inc_spouse_all2009
ren ER48615 inc_spouse_all2011
ren ER54309 inc_spouse_all2013
ren ER61349 inc_spouse_all2015
ren ER16471 total_hours_head1999
ren ER20399 total_hours_head2001
ren ER24080 total_hours_head2003
ren ER27886 total_hours_head2005
ren ER40876 total_hours_head2007
ren ER46767 total_hours_head2009
ren ER52175 total_hours_head2011
ren ER57976 total_hours_head2013
ren ER65156 total_hours_head2015
ren ER16482 total_hours_spouse1999
ren ER20410 total_hours_spouse2001
ren ER24091 total_hours_spouse2003
ren ER27897 total_hours_spouse2005
ren ER40887 total_hours_spouse2007
ren ER46788 total_hours_spouse2009
ren ER52196 total_hours_spouse2011
ren ER57997 total_hours_spouse2013
ren ER65177 total_hours_spouse2015
ren ER16514 wage_rate_head1999
ren ER20451 wage_rate_head2001
ren ER24137 wage_rate_head2003
ren ER28003 wage_rate_head2005
ren ER40993 wage_rate_head2007
ren ER46901 wage_rate_head2009
ren ER52309 wage_rate_head2011
ren ER58118 wage_rate_head2013
ren ER65315 wage_rate_head2015
ren ER16515 wage_rate_spouse1999
ren ER20452 wage_rate_spouse2001
ren ER24138 wage_rate_spouse2003
ren ER28004 wage_rate_spouse2005
ren ER40994 wage_rate_spouse2007
ren ER46902 wage_rate_spouse2009
ren ER52310 wage_rate_spouse2011
ren ER58119 wage_rate_spouse2013
ren ER65316 wage_rate_spouse2015
ren ER16454 inc_transfer1999
ren ER20450 inc_transfer2001
ren ER24101 inc_transfer2003
ren ER28002 inc_transfer2005
ren ER40992 inc_transfer2007
ren ER46900 inc_transfer2009
ren ER52308 inc_transfer2011
ren ER58117 inc_transfer2013
ren ER65314 inc_transfer2015
ren ER28031 inc_ss_head2005
ren ER41021 inc_ss_head2007
ren ER46929 inc_ss_head2009
ren ER52337 inc_ss_head2011
ren ER58146 inc_ss_head2013
ren ER65343 inc_ss_head2015
ren ER28033 inc_ss_spouse2005
ren ER41023 inc_ss_spouse2007
ren ER46931 inc_ss_spouse2009
ren ER52339 inc_ss_spouse2011
ren ER58148 inc_ss_spouse2013
ren ER65345 inc_ss_spouse2015
ren ER28035 inc_ss_ofum2005
ren ER41025 inc_ss_ofum2007
ren ER46933 inc_ss_ofum2009
ren ER52341 inc_ss_ofum2011
ren ER58150 inc_ss_ofum2013
ren ER65347 inc_ss_ofum2015
ren ER16460 inc_ss_fam1999
ren ER20455 inc_ss_fam2001
ren ER24104 inc_ss_fam2003
ren ER34376 year_left_college2015
ren ER16515A1 foodexpenditure1999
ren ER20456A1 foodexpenditure2001
ren ER24138A1 foodexpenditure2003
ren ER28037A1 foodexpenditure2005
ren ER41027A1 foodexpenditure2007
ren ER46971A1 foodexpenditure2009
ren ER52395A1 foodexpenditure2011
ren ER58212A1 foodexpenditure2013
ren ER65410 foodexpenditure2015
ren ER16515A2 foodathomeexpenditure1999
ren ER20456A2 foodathomeexpenditure2001
ren ER24138A2 foodathomeexpenditure2003
ren ER28037A2 foodathomeexpenditure2005
ren ER41027A2 foodathomeexpenditure2007
ren ER46971A2 foodathomeexpenditure2009
ren ER52395A2 foodathomeexpenditure2011
ren ER58212A2 foodathomeexpenditure2013
ren ER65411 foodathomeexpenditure2015
ren ER16515A3 foodawayfromhomeexpenditure1999
ren ER20456A3 foodawayfromhomeexpenditure2001
ren ER24138A3 foodawayfromhomeexpenditure2003
ren ER28037A3 foodawayfromhomeexpenditure2005
ren ER41027A3 foodawayfromhomeexpenditure2007
ren ER46971A3 foodawayfromhomeexpenditure2009
ren ER52395A3 foodawayfromhomeexpenditure2011
ren ER58212A3 foodawayfromhomeexpenditure2013
ren ER65412 foodawayfromhomeexpenditure2015
ren ER16515A4 fooddeliveredexpenditure1999
ren ER20456A4 fooddeliveredexpenditure2001
ren ER24138A4 fooddeliveredexpenditure2003
ren ER28037A4 fooddeliveredexpenditure2005
ren ER41027A4 fooddeliveredexpenditure2007
ren ER46971A4 fooddeliveredexpenditure2009
ren ER52395A4 fooddeliveredexpenditure2011
ren ER58212A4 fooddeliveredexpenditure2013
ren ER65413 fooddeliveredexpenditure2015
ren ER14256 foodstamp1999
ren ER18387 foodstamp2001
ren ER21653 foodstamp2003
ren ER25655 foodstamp2005
ren ER36673 foodstamp2007
ren ER42692 foodstamp2009
ren ER48008 foodstamp2011
ren ER53705 foodstamp2013
ren ER60720 foodstamp2015
ren ER16515A5 housingexpenditure1999
ren ER20456A5 housingexpenditure2001
ren ER24138A5 housingexpenditure2003
ren ER28037A5 housingexpenditure2005
ren ER41027A5 housingexpenditure2007
ren ER46971A5 housingexpenditure2009
ren ER52395A5 housingexpenditure2011
ren ER58212A5 housingexpenditure2013
ren ER65414 housingexpenditure2015
ren ER16515A6 mortgageexpenditure1999
ren ER20456A6 mortgageexpenditure2001
ren ER24138A6 mortgageexpenditure2003
ren ER28037A6 mortgageexpenditure2005
ren ER41027A6 mortgageexpenditure2007
ren ER46971A6 mortgageexpenditure2009
ren ER52395A6 mortgageexpenditure2011
ren ER58212A6 mortgageexpenditure2013
ren ER65415 mortgageexpenditure2015
ren ER16515A7 rentexpenditure1999
ren ER20456A7 rentexpenditure2001
ren ER24138A7 rentexpenditure2003
ren ER28037A7 rentexpenditure2005
ren ER41027A7 rentexpenditure2007
ren ER46971A7 rentexpenditure2009
ren ER52395A7 rentexpenditure2011
ren ER58212A7 rentexpenditure2013
ren ER65416 rentexpenditure2015
ren ER16515A8 propertytaxexpenditure1999
ren ER20456A8 propertytaxexpenditure2001
ren ER24138A8 propertytaxexpenditure2003
ren ER28037A8 propertytaxexpenditure2005
ren ER41027A8 propertytaxexpenditure2007
ren ER46971A8 propertytaxexpenditure2009
ren ER52395A8 propertytaxexpenditure2011
ren ER58212A8 propertytaxexpenditure2013
ren ER65417 propertytaxexpenditure2015
ren ER16515A9 homeinsuranceexpenditure1999
ren ER20456A9 homeinsuranceexpenditure2001
ren ER24138A9 homeinsuranceexpenditure2003
ren ER28037A9 homeinsuranceexpenditure2005
ren ER41027A9 homeinsuranceexpenditure2007
ren ER46971A9 homeinsuranceexpenditure2009
ren ER52395A9 homeinsuranceexpenditure2011
ren ER58212A9 homeinsuranceexpenditure2013
ren ER65418 homeinsuranceexpenditure2015
ren ER16515B1 utilityexpenditure1999
ren ER20456B1 utilityexpenditure2001
ren ER24138B1 utilityexpenditure2003
ren ER28037B1 utilityexpenditure2005
ren ER41027B1 utilityexpenditure2007
ren ER46971B1 utilityexpenditure2009
ren ER52395B1 utilityexpenditure2011
ren ER58212B1 utilityexpenditure2013
ren ER65419 utilityexpenditure2015
ren ER16515B6 transportationexpenditure1999
ren ER20456B6 transportationexpenditure2001
ren ER24138B6 transportationexpenditure2003
ren ER28037B7 transportationexpenditure2005
ren ER41027B7 transportationexpenditure2007
ren ER46971B7 transportationexpenditure2009
ren ER52395B7 transportationexpenditure2011
ren ER58212B7 transportationexpenditure2013
ren ER65425 transportationexpenditure2015
ren ER16515B7 vehicleloanexpenditure1999
ren ER20456B7 vehicleloanexpenditure2001
ren ER24138B7 vehicleloanexpenditure2003
ren ER28037B8 vehicleloanexpenditure2005
ren ER41027B8 vehicleloanexpenditure2007
ren ER46971B8 vehicleloanexpenditure2009
ren ER52395B8 vehicleloanexpenditure2011
ren ER58212B8 vehicleloanexpenditure2013
ren ER65426 vehicleloanexpenditure2015
ren ER16515B8 vehicledpexpenditure1999
ren ER20456B8 vehicledpexpenditure2001
ren ER24138B8 vehicledpexpenditure2003
ren ER28037B9 vehicledpexpenditure2005
ren ER41027B9 vehicledpexpenditure2007
ren ER46971B9 vehicledpexpenditure2009
ren ER52395B9 vehicledpexpenditure2011
ren ER58212B9 vehicledpexpenditure2013
ren ER65427 vehicledpexpenditure2015
ren ER16515B9 vehicleleaseexpenditure1999
ren ER20456B9 vehicleleaseexpenditure2001
ren ER24138B9 vehicleleaseexpenditure2003
ren ER28037C1 vehicleleaseexpenditure2005
ren ER41027C1 vehicleleaseexpenditure2007
ren ER46971C1 vehicleleaseexpenditure2009
ren ER52395C1 vehicleleaseexpenditure2011
ren ER58212C1 vehicleleaseexpenditure2013
ren ER65428 vehicleleaseexpenditure2015
ren ER16515C1 autoinsexpenditure1999
ren ER20456C1 autoinsexpenditure2001
ren ER24138C1 autoinsexpenditure2003
ren ER28037C2 autoinsexpenditure2005
ren ER41027C2 autoinsexpenditure2007
ren ER46971C2 autoinsexpenditure2009
ren ER52395C2 autoinsexpenditure2011
ren ER58212C2 autoinsexpenditure2013
ren ER65429 autoinsexpenditure2015
ren ER16515C2 addvehicleexpenditure1999
ren ER20456C2 addvehicleexpenditure2001
ren ER24138C2 addvehicleexpenditure2003
ren ER28037C3 addvehicleexpenditure2005
ren ER41027C3 addvehicleexpenditure2007
ren ER46971C3 addvehicleexpenditure2009
ren ER52395C3 addvehicleexpenditure2011
ren ER58212C3 addvehicleexpenditure2013
ren ER65430 addvehicleexpenditure2015
ren ER16515C3 vehiclerepairexpenditure1999
ren ER20456C3 vehiclerepairexpenditure2001
ren ER24138C3 vehiclerepairexpenditure2003
ren ER28037C4 vehiclerepairexpenditure2005
ren ER41027C4 vehiclerepairexpenditure2007
ren ER46971C4 vehiclerepairexpenditure2009
ren ER52395C4 vehiclerepairexpenditure2011
ren ER58212C4 vehiclerepairexpenditure2013
ren ER65431 vehiclerepairexpenditure2015
ren ER16515C4 gasolineexpenditure1999
ren ER20456C4 gasolineexpenditure2001
ren ER24138C4 gasolineexpenditure2003
ren ER28037C5 gasolineexpenditure2005
ren ER41027C5 gasolineexpenditure2007
ren ER46971C5 gasolineexpenditure2009
ren ER52395C5 gasolineexpenditure2011
ren ER58212C5 gasolineexpenditure2013
ren ER65432 gasolineexpenditure2015
ren ER16515C5 parkingexpenditure1999
ren ER20456C5 parkingexpenditure2001
ren ER24138C5 parkingexpenditure2003
ren ER28037C6 parkingexpenditure2005
ren ER41027C6 parkingexpenditure2007
ren ER46971C6 parkingexpenditure2009
ren ER52395C6 parkingexpenditure2011
ren ER58212C6 parkingexpenditure2013
ren ER65433 parkingexpenditure2015
ren ER16515C6 bustrainexpenditure1999
ren ER20456C6 bustrainexpenditure2001
ren ER24138C6 bustrainexpenditure2003
ren ER28037C7 bustrainexpenditure2005
ren ER41027C7 bustrainexpenditure2007
ren ER46971C7 bustrainexpenditure2009
ren ER52395C7 bustrainexpenditure2011
ren ER58212C7 bustrainexpenditure2013
ren ER65434 bustrainexpenditure2015
ren ER16515C7 taxiexpenditure1999
ren ER20456C7 taxiexpenditure2001
ren ER24138C7 taxiexpenditure2003
ren ER28037C8 taxiexpenditure2005
ren ER41027C8 taxiexpenditure2007
ren ER46971C8 taxiexpenditure2009
ren ER52395C8 taxiexpenditure2011
ren ER58212C8 taxiexpenditure2013
ren ER65435 taxiexpenditure2015
ren ER16515C8 othertransexpenditure1999
ren ER20456C8 othertransexpenditure2001
ren ER24138C8 othertransexpenditure2003
ren ER28037C9 othertransexpenditure2005
ren ER41027C9 othertransexpenditure2007
ren ER46971C9 othertransexpenditure2009
ren ER52395C9 othertransexpenditure2011
ren ER58212C9 othertransexpenditure2013
ren ER65436 othertransexpenditure2015
ren ER16515C9 educationexpenditure1999
ren ER20456C9 educationexpenditure2001
ren ER24138C9 educationexpenditure2003
ren ER28037D1 educationexpenditure2005
ren ER41027D1 educationexpenditure2007
ren ER46971D1 educationexpenditure2009
ren ER52395D1 educationexpenditure2011
ren ER58212D1 educationexpenditure2013
ren ER65437 educationexpenditure2015
ren ER16515D1 childcareexpenditure1999
ren ER20456D1 childcareexpenditure2001
ren ER24138D1 childcareexpenditure2003
ren ER28037D2 childcareexpenditure2005
ren ER41027D2 childcareexpenditure2007
ren ER46971D2 childcareexpenditure2009
ren ER52395D2 childcareexpenditure2011
ren ER58212D2 childcareexpenditure2013
ren ER65438 childcareexpenditure2015
ren ER16515D2 healthcareexpenditure1999
ren ER20456D2 healthcareexpenditure2001
ren ER24138D2 healthcareexpenditure2003
ren ER28037D3 healthcareexpenditure2005
ren ER41027D3 healthcareexpenditure2007
ren ER46971D3 healthcareexpenditure2009
ren ER52395D3 healthcareexpenditure2011
ren ER58212D3 healthcareexpenditure2013
ren ER65439 healthcareexpenditure2015
ren ER16515D6 healthinsuranceexpenditure1999
ren ER20456D6 healthinsuranceexpenditure2001
ren ER24138D6 healthinsuranceexpenditure2003
ren ER28037D7 healthinsuranceexpenditure2005
ren ER41027D7 healthinsuranceexpenditure2007
ren ER46971D7 healthinsuranceexpenditure2009
ren ER52395D7 healthinsuranceexpenditure2011
ren ER58212D7 healthinsuranceexpenditure2013
ren ER65443 healthinsuranceexpenditure2015
ren ER28037B6 telephoneexpenditure2005
ren ER41027B6 telephoneexpenditure2007
ren ER46971B6 telephoneexpenditure2009
ren ER52395B6 telephoneexpenditure2011
ren ER58212B6 telephoneexpenditure2013
ren ER65424 telephoneexpenditure2015
ren ER28037D8 repairsexpenditure2005
ren ER41027D8 repairsexpenditure2007
ren ER46971D8 repairsexpenditure2009
ren ER52395D8 repairsexpenditure2011
ren ER58212D8 repairsexpenditure2013
ren ER65444 repairsexpenditure2015
ren ER28037D9 furnishingsexpenditure2005
ren ER41027D9 furnishingsexpenditure2007
ren ER46971D9 furnishingsexpenditure2009
ren ER52395D9 furnishingsexpenditure2011
ren ER58212D9 furnishingsexpenditure2013
ren ER65445 furnishingsexpenditure2015
ren ER28037E1 clothingexpenditure2005
ren ER41027E1 clothingexpenditure2007
ren ER46971E1 clothingexpenditure2009
ren ER52395E1 clothingexpenditure2011
ren ER58212E1 clothingexpenditure2013
ren ER65446 clothingexpenditure2015
ren ER28037E2 tripsexpenditure2005
ren ER41027E2 tripsexpenditure2007
ren ER46971E2 tripsexpenditure2009
ren ER52395E2 tripsexpenditure2011
ren ER58212E2 tripsexpenditure2013
ren ER65447 tripsexpenditure2015
ren ER28037E3 recreationexpenditure2005
ren ER41027E3 recreationexpenditure2007
ren ER46971E3 recreationexpenditure2009
ren ER52395E3 recreationexpenditure2011
ren ER58212E3 recreationexpenditure2013
ren ER65448 recreationexpenditure2015
ren S416 fam_wealth_ex_home1999
ren S516 fam_wealth_ex_home2001
ren S616 fam_wealth_ex_home2003
ren S716 fam_wealth_ex_home2005
ren S816 fam_wealth_ex_home2007
ren ER46968 fam_wealth_ex_home2009
ren ER52392 fam_wealth_ex_home2011
ren ER58209 fam_wealth_ex_home2013
ren ER65406 fam_wealth_ex_home2015
ren S417 fam_wealth1999
ren S517 fam_wealth2001
ren S617 fam_wealth2003
ren S717 fam_wealth2005
ren S817 fam_wealth2007
ren ER46970 fam_wealth2009
ren ER52394 fam_wealth2011
ren ER58211 fam_wealth2013
ren ER65408 fam_wealth2015
ren S405 bank_account_wealth1999
ren S505 bank_account_wealth2001
ren S605 bank_account_wealth2003
ren S705 bank_account_wealth2005
ren S805 bank_account_wealth2007
ren ER46942 bank_account_wealth2009
ren ER52350 bank_account_wealth2011
ren ER58161 bank_account_wealth2013
ren ER65358 bank_account_wealth2015
ren S419 IRA_wealth1999
ren S519 IRA_wealth2001
ren S619 IRA_wealth2003
ren S719 IRA_wealth2005
ren S819 IRA_wealth2007
ren ER46964 IRA_wealth2009
ren ER52368 IRA_wealth2011
ren ER58181 IRA_wealth2013
ren ER65378 IRA_wealth2015
ren S411 stock_wealth1999
ren S511 stock_wealth2001
ren S611 stock_wealth2003
ren S711 stock_wealth2005
ren S811 stock_wealth2007
ren ER46954 stock_wealth2009
ren ER52358 stock_wealth2011
ren ER58171 stock_wealth2013
ren ER65368 stock_wealth2015
ren S403 business_wealth1999
ren S503 business_wealth2001
ren S603 business_wealth2003
ren S703 business_wealth2005
ren S803 business_wealth2007
ren ER46938 business_wealth2009
ren ER52346 business_wealth2011
ren ER58155 business_value2013
ren ER65352 business_value2015
ren ER58157 business_debt2013
ren ER65354 business_debt2015
ren S409 other_real_estate_wealth1999
ren S509 other_real_estate_wealth2001
ren S609 other_real_estate_wealth2003
ren S709 other_real_estate_wealth2005
ren S809 other_real_estate_wealth2007
ren ER46950 other_real_estate_wealth2009
ren ER52354 other_real_estate_wealth2011
ren ER58165 other_real_estate_value2013
ren ER65362 other_real_estate_value2015
ren ER58167 other_real_estate_debt2013
ren ER65364 other_real_estate_debt2015
ren ER13041 housevalue1999
ren ER17044 housevalue2001
ren ER21043 housevalue2003
ren ER25029 housevalue2005
ren ER36029 housevalue2007
ren ER42030 housevalue2009
ren ER47330 housevalue2011
ren ER53030 housevalue2013
ren ER60031 housevalue2015
ren S420 homeequity1999
ren S520 homeequity2001
ren S620 homeequity2003
ren S720 homeequity2005
ren S820 homeequity2007
ren ER46966 homeequity2009
ren ER52390 homeequity2011
ren ER58207 homeequity2013
ren ER65404 homeequity2015
ren S420A acc_homeequity1999
ren S520A acc_homeequity2001
ren S620A acc_homeequity2003
ren S720A acc_homeequity2005
ren S820A acc_homeequity2007
ren ER46967 acc_homeequity2009
ren ER52391 acc_homeequity2011
ren ER58208 acc_homeequity2013
ren ER65405 acc_homeequity2015
ren ER13040 housingstatus1999
ren ER17043 housingstatus2001
ren ER21042 housingstatus2003
ren ER25028 housingstatus2005
ren ER36028 housingstatus2007
ren ER42029 housingstatus2009
ren ER47329 housingstatus2011
ren ER53029 housingstatus2013
ren ER60030 housingstatus2015
ren ER13045 type_mortgage11999
ren ER17050 type_mortgage12001
ren ER21049 type_mortgage12003
ren ER25040 type_mortgage12005
ren ER36040 type_mortgage12007
ren ER42041 type_mortgage12009
ren ER47346 type_mortgage12011
ren ER53046 type_mortgage12013
ren ER60047 type_mortgage12015
ren ER13054 type_mortgage21999
ren ER17061 type_mortgage22001
ren ER21060 type_mortgage22003
ren ER25051 type_mortgage22005
ren ER36052 type_mortgage22007
ren ER42060 type_mortgage22009
ren ER47367 type_mortgage22011
ren ER53067 type_mortgage22013
ren ER60068 type_mortgage22015
ren ER13047 mortgage11999
ren ER17052 mortgage12001
ren ER21051 mortgage12003
ren ER25042 mortgage12005
ren ER36042 mortgage12007
ren ER42043 mortgage12009
ren ER47348 mortgage12011
ren ER53048 mortgage12013
ren ER60049 mortgage12015
ren ER13056 mortgage21999
ren ER17063 mortgage22001
ren ER21062 mortgage22003
ren ER25053 mortgage22005
ren ER36054 mortgage22007
ren ER42062 mortgage22009
ren ER47369 mortgage22011
ren ER53069 mortgage22013
ren ER60070 mortgage22015
ren ER13037 room_count1999
ren ER17040 room_count2001
ren ER21039 room_count2003
ren ER25027 room_count2005
ren ER36027 room_count2007
ren ER42028 room_count2009
ren ER47328 room_count2011
ren ER53028 room_count2013
ren ER60029 room_count2015
ren ER13079 year_moved1999
ren ER17090 year_moved2001
ren ER21119 year_moved2003
ren ER25100 year_moved2005
ren ER36105 year_moved2007
ren ER42134 year_moved2009
ren ER47442 year_moved2011
ren ER53142 year_moved2013
ren ER60157 year_moved2015
ren ER13078 month_moved1999
ren ER17089 month_moved2001
ren ER21118 month_moved2003
ren ER25099 month_moved2005
ren ER36104 month_moved2007
ren ER42133 month_moved2009
ren ER47441 month_moved2011
ren ER53141 month_moved2013
ren ER60156 month_moved2015
ren ER13005 current_state1999
ren ER17005 current_state2001
ren ER21004 current_state2003
ren ER25004 current_state2005
ren ER36004 current_state2007
ren ER42004 current_state2009
ren ER47304 current_state2011
ren ER53004 current_state2013
ren ER60004 current_state2015
ren ER15115 received_gift1999
ren ER19311 received_gift2001
ren ER22706 received_gift2003
ren ER26687 received_gift2005
ren ER37705 received_gift2007
ren ER43696 received_gift2009
ren ER49041 received_gift2011
ren ER54797 received_gift2013
ren ER61908 received_gift2015
ren ER15116 year_gift_11999
ren ER19312 year_gift_12001
ren ER22707 year_gift_12003
ren ER26688 year_gift_12005
ren ER37706 year_gift_12007
ren ER43697 year_gift_12009
ren ER49042 year_gift_12011
ren ER54798 year_gift_12013
ren ER61910 year_gift_12015
ren ER15117 value_gift_11999
ren ER19313 value_gift_12001
ren ER22708 value_gift_12003
ren ER26689 value_gift_12005
ren ER37707 value_gift_12007
ren ER43698 value_gift_12009
ren ER49043 value_gift_12011
ren ER54799 value_gift_12013
ren ER61913 value_gift_12015
ren ER15121 year_gift_21999
ren ER19317 year_gift_22001
ren ER22712 year_gift_22003
ren ER26693 year_gift_22005
ren ER37711 year_gift_22007
ren ER43702 year_gift_22009
ren ER49047 year_gift_22011
ren ER54803 year_gift_22013
ren ER61918 year_gift_22015
ren ER15122 value_gift_21999
ren ER19318 value_gift_22001
ren ER22713 value_gift_22003
ren ER26694 value_gift_22005
ren ER37712 value_gift_22007
ren ER43703 value_gift_22009
ren ER49048 value_gift_22011
ren ER54804 value_gift_22013
ren ER61921 value_gift_22015
ren ER15126 year_gift_31999
ren ER19322 year_gift_32001
ren ER22717 year_gift_32003
ren ER26698 year_gift_32005
ren ER37716 year_gift_32007
ren ER43707 year_gift_32009
ren ER49052 year_gift_32011
ren ER54808 year_gift_32013
ren ER61926 year_gift_32015
ren ER15127 value_gift_31999
ren ER19323 value_gift_32001
ren ER22718 value_gift_32003
ren ER26699 value_gift_32005
ren ER37717 value_gift_32007
ren ER43708 value_gift_32009
ren ER49053 value_gift_32011
ren ER54809 value_gift_32013
ren ER61929 value_gift_32015
ren ER33546 indiv_longitudinal_weight1999
ren ER33637 indiv_longitudinal_weight2001
ren ER33740 indiv_longitudinal_weight2003
ren ER33848 indiv_longitudinal_weight2005
ren ER33950 indiv_longitudinal_weight2007
ren ER34045 indiv_longitudinal_weight2009
ren ER34154 indiv_longitudinal_weight2011
ren ER34268 indiv_longitudinal_weight2013
ren ER34413 indiv_longitudinal_weight2015
ren ER33547 indiv_cross_sec_weight1999
ren ER33639 indiv_cross_sec_weight2001
ren ER33742 indiv_cross_sec_weight2003
ren ER33849 indiv_cross_sec_weight2005
ren ER33951 indiv_cross_sec_weight2007
ren ER34046 indiv_cross_sec_weight2009
ren ER34155 indiv_cross_sec_weight2011
ren ER34269 indiv_cross_sec_weight2013
ren ER34414 indiv_cross_sec_weight2015
ren ER16518 family_weight1999
ren ER20394 family_weight2001
ren ER24179 family_weight2003
ren ER28078 family_weight2005
ren ER41069 family_weight2007
ren ER47012 family_weight2009
ren ER52436 family_weight2011
ren ER58257 family_weight2013
ren ER65492 family_weight2015
order x11101ll x11102* xsqnr_* rel2head* age* year_born* sex_head* sex_indiv* deathyr* month* fchg* splitoff_indicator* age_spouse* children* married* racehead* educhead* educspouse* spouse_mother_educlevel* spouse_father_educlevel* fsize* region* metro_pre2015* metro_2015* emp_status_head* emp_status_head_2* emp_status_head_3* ret_year* why_last_job_end* months_out_lab_force* emp_status_spouse* emp_status_spouse_2* emp_status_spouse_3* ret_year_spouse* why_last_job_end_spouse* emp_status_indiv* inc_fam* inc_head* inc_spouse* inc_spouse_all* total_hours_head* total_hours_spouse* wage_rate_head* wage_rate_spouse* inc_transfer* inc_ss_head* inc_ss_spouse* inc_ss_ofum* inc_ss_fam* year_left_college* foodexpenditure* foodathomeexpenditure* foodawayfromhomeexpenditure* fooddeliveredexpenditure* foodstamp* housingexpenditure* mortgageexpenditure* rentexpenditure* propertytaxexpenditure* homeinsuranceexpenditure* utilityexpenditure* transportationexpenditure* vehicleloanexpenditure* vehicledpexpenditure* vehicleleaseexpenditure* autoinsexpenditure* addvehicleexpenditure* vehiclerepairexpenditure* gasolineexpenditure* parkingexpenditure* bustrainexpenditure* taxiexpenditure* othertransexpenditure* educationexpenditure* childcareexpenditure* healthcareexpenditure* healthinsuranceexpenditure* telephoneexpenditure* repairsexpenditure* furnishingsexpenditure* clothingexpenditure* tripsexpenditure* recreationexpenditure* fam_wealth_ex_home* fam_wealth* bank_account_wealth* IRA_wealth* stock_wealth* business_wealth* business_value* business_debt* other_real_estate_wealth* other_real_estate_value* other_real_estate_debt* housevalue* homeequity* acc_homeequity* housingstatus* type_mortgage1* type_mortgage2* mortgage1* mortgage2* room_count* year_moved* month_moved* current_state* received_gift* year_gift_1* value_gift_1* year_gift_2* value_gift_2* year_gift_3* value_gift_3* indiv_longitudinal_weight* indiv_cross_sec_weight* family_weight*

