	lab var ret_duration "Duration of Head's Retirement"
	lab var transportation_blundell "Transportation Services"
	lab var gasolineexpenditure "Gasoline Expenditure"
	lab var healthcareexpenditure "Health care"
	lab var healthinsuranceexpenditure "Health insurance"
	lab var healthservicesexpenditure "Health services"
	lab var tripsexpenditure "Trips"
	lab var recreationexpenditure "Recreation"
	lab var clothingexpenditure "Clothing"
	lab var foodathomeexpenditure "Food at home"
	lab var foodawayfromhomeexpenditure "Food away from home"
	lab var expenditure_blundell_eq "Nondurable Consumption (Equivalence Scale)"
	lab var workexpenditure "Work Related Expenditure" // excludes clothing

	lab var expenditure_cats_2005 "Expenditure Categories"
	lab var total_foodexp_home_real "Food Expenditure at Home"
	lab var total_foodexp_away_real "Food away from Home"
	lab var	total_education_real "Education Expenditure"
	lab var	total_healthexpense_real "Health Expenditure"
	lab var	total_transport_real "Non Durables Transportation Expenditure"
	lab var	transport_durables "Transportation Durables Expenditure"
	lab var	total_housing_2005_real "Housing Expenditure"
	lab var	total_recreation_2005_real "Recreation Expenditure"
	lab var total_clothing_2005_real  "Clothing Expenditure"